# .github/workflows/build-windows.yml

name: Build and Release Windows Application

on:
  release:
    types: [published] # 当一个 Release 被发布（而不是草稿）时触发

jobs:
  build:
    runs-on: windows-latest
    
    # 【新增】: 授予 workflow 写入 Release 的权限
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install Fyne dependencies
        run: choco install mingw

      # 【修改点 1】: 使用新的官方推荐路径安装 fyne 工具
      - name: Install Fyne command
        run: go install fyne.io/tools/cmd/fyne@latest

      # 【修改点 2】: 修改打包步骤
      - name: Package Windows application
        shell: pwsh
        # 新增 env: 来设置环境变量
        env:
          # 将 ldflags 的内容通过 CGO_LDFLAGS 环境变量传递
          CGO_LDFLAGS: "-H windowsgui"
        run: |
          # 定义应用名称和版本号
          # 直接从触发事件的 release 中获取 tag_name 作为版本号
          $appName = "yanshu-toolkit"
          $appVersion = "${{ github.event.release.tag_name }}"
          
          # 定义最终的打包文件名
          $outputFileName = "$appName-windows-$appVersion.exe"
          
          # 执行打包命令
          fyne package -os windows -icon assets/icon/app.png -name "$outputFileName"
          
      - name: Upload to Release Assets
        uses: softprops/action-gh-release@v2
        with:
          # files 参数指定要上传的文件路径
          # 支持通配符，这里我们直接指定打包好的 .exe 文件
          files: yanshu-toolkit-windows-*.exe